item {
    name: "Adidas",
    id: 1,
    display_name: "Adidas"
}
item {
    name: "Nike",
    id: 9,
    display_name: "Nike"
}
item {
    name: "Puma",
    id: 11,
    display_name: "Puma"
}
item {
    name: "TheNorthFace",
    id: 13,
    display_name: "TheNorthFace"
}
item {
    name: "UnderArmour",
    id: 15,
    display_name: "UnderArmour"
}